name: GitHub metrics
on:
  schedule:
    - cron: "30 5 * * *"
  push:
    branches: "master"
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
  
      - name: Personal metrics
        uses: theashishgavade/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories"
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_music: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_sort: random
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_stargazers: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_people: yes
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 14
          plugin_reactions_details: percentage
          plugin_achievements: yes
          plugin_achievements_threshold: C       
          plugin_achievements_secrets: yes   
          plugin_achievements_limit: 0
          plugin_support: yes
          
      - name: Personal metrics (detailed)
        uses: Theashishgavade/metrics@master
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"
          plugin_gists: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_pagespeed_screenshot: yes
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_people_user: .github.user 
          plugin_posts_limit: 4            
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes   
          config_timezone: Asia/Kolkata
          plugin_languages_colors : "rainbow"
