name: GitHub metrics
on:
  schedule:
    - cron: "30 5 * * *"
  push:
    branches: "master"
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
  
      - name: Personal metrics
        uses: theashishgavade/metrics@master
        with:
          filename: metrics.svg
                   
      - name: Personal metrics (detailed)
        uses: Theashishgavade/metrics@master
        with:
          filename: metrics.detailed.svg
         
